# Generated by Django 4.1.1 on 2022-09-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('cdi', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('apellidomaterno', models.CharField(max_length=35)),
                ('apellidopaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('profesion', models.CharField(max_length=90)),
                ('Fecha_de_Integración', models.DateField(auto_now_add=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materias')),
            ],
        ),
    ]
